version: "3"
services:
  configuration-store:
    build: ./etcd
    networks:
      config:
        aliases:
          - cstore
  load-balancer:
    ports:
      - "80:80"
    build: ./nginx
    networks:
      config:
      workers:
  queue:
    image: redis:alpine
networks:
  config:
  workers:
