version: "3"
services:
  configuration-store:
    build: ./etcd
    networks:
      config:
        aliases:
          - cstore
  load-balancer:
    ports:
      - "127.0.0.1:80:80"
    build: ./nginx
    networks:
      - config
      - workers
    depends_on:
      - configuration-store
      - fetcher
  queue:
    image: redis:alpine
    networks:
      workers:
        aliases:
          - queue
  fetcher:
    build: ./fetcher
    networks:
      - workers
    depends_on:
      - configuration-store
      - queue
networks:
  config:
  workers:

