version: "3"
services:
  configuration-store:
    build: ./etcd
    networks:
      config:
        aliases:
          - cstore
  load-balancer:
    ports:
      - "127.0.0.1:80:80/tcp"
    build: ./nginx
    networks:
      - config
      - fetchers
    depends_on:
      - configuration-store
      - fetcher
  queue:
    image: redis:alpine
    networks:
      fetchers:
        aliases:
          - queue
      processors:
        aliases:
          - queue
  fetcher:
    build: ./fetcher
    networks:
      - fetchers
    depends_on:
      - configuration-store
      - queue
  processor:
    build: ./processor
    networks:
      - processors
    depends_on:
      - queue
  prometheus:
    build: ./prometheus
    ports:
      - "127.0.0.1:9090:9090/tcp"
    networks:
      - fetchers
      - processors
      - monitoring
  grafana:
    build: ./grafana
    ports:
      - "127.0.0.1:3000:3000/tcp"
    networks:
      - monitoring
networks:
  config:
  fetchers:
  processors:
  monitoring:

